name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Change to your default branch if it's not 'main' (e.g., 'master')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the Node version your app needs (e.g., 16, 20)

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Build the React app
      - name: Build
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub
          publish_dir: ./build  # Folder containing the built app (change if not 'build')
